language: ruby
script: 'bundle exec rake db:migrate && bundle exec rspec spec/'
rvm:
  - 1.9.3
env:
notifications:
  email: 
    james@jamesrgifford.com
    fusion94@gmail.com
# whitelist    
branches:
  only:
    - master
